--extractor-args youtubepot-bgutilhttp:base_url=http://127.0.0.1:4416
--extractor-args youtube:player_client=visionos,android
--geo-bypass
--no-check-certificate
--socket-timeout 10
--no-warnings

--concurrent-fragments 5

--no-js-runtimes
--js-runtimes node
